export let Api = [
  {
    id: 1,
    company: "Photosnap",
    logo: "../static-job-listings-master/images/photosnap.svg",
    new: true,
    featured: true,
    position: "Senior Frontend Developer",
    role: "Frontend",
    level: "Senior",
    timePosted: "1d ago",
    contract: "Full Time",
    location: "USA Only",
    progLanguage: ["HTML", "CSS", "JavaScript"],
    tools: [],
  },
  {
    id: 2,
    company: "Manage",
    logo: "../static-job-listings-master/images/manage.svg",
    new: true,
    featured: true,
    position: "Fullstack Developer",
    role: "Fullstack",
    level: "Midweight",
    timePosted: "1d ago",
    contract: "Part Time",
    location: "Remote",
    progLanguage: ["Python"],
    tools: ["React"],
  },
  {
    id: 3,
    company: "Account",
    logo: "../static-job-listings-master/images/account.svg",
    new: true,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    timePosted: "2d ago",
    contract: "Part Time",
    location: "USA Only",
    progLanguage: ["JavaScript"],
    tools: ["React", "Sass"],
  },
  {
    id: 4,
    company: "MyHome",
    logo: "../static-job-listings-master/images/myhome.svg",
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    timePosted: "5d ago",
    contract: "Contract",
    location: "USA Only",
    progLanguage: ["CSS", "JavaScript"],
    tools: [],
  },
  {
    id: 5,
    company: "Loop Studios",
    logo: "../static-job-listings-master/images/loop-studios.svg",
    new: false,
    featured: false,
    position: "Software Engineer",
    role: "Fullstack",
    level: "Midweight",
    timePosted: "1w ago",
    contract: "Full Time",
    location: "Worldwide",
    progLanguage: ["JavaScript"],
    tools: [],
  },
  {
    id: 6,
    company: "FaceIt",
    logo: "../static-job-listings-master/images/faceit.svg",
    new: false,
    featured: false,
    position: "Junior Backend Developer",
    role: "Backend",
    level: "Junior",
    timePosted: "2w ago",
    contract: "Full Time",
    location: "UK Only",
    progLanguage: ["Ruby"],
    tools: ["RoR"],
  },
  {
    id: 7,
    company: "Shortly",
    logo: "../static-job-listings-master/images/shortly.svg",
    new: false,
    featured: false,
    position: "Junior Developer",
    role: "Frontend",
    level: "Junior",
    timePosted: "2w ago",
    contract: "Full Time",
    location: "Worldwide",
    progLanguage: ["HTML", "JavaScript"],
    tools: ["Sass"],
  },
  {
    id: 8,
    company: "Insure",
    logo: "../static-job-listings-master/images/insure.svg",
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    timePosted: "2w ago",
    contract: "Full Time",
    location: "USA Only",
    progLanguage: ["JavaScript"],
    tools: ["Vue", "Sass"],
  },
  {
    id: 9,
    company: "Eyecam Co.",
    logo: "../static-job-listings-master/images/eyecam-co.svg",
    new: false,
    featured: false,
    position: "Full Stack Engineer",
    role: "Fullstack",
    level: "Midweight",
    timePosted: "3w ago",
    contract: "Full Time",
    location: "Worldwide",
    progLanguage: ["JavaScript", "Python"],
    tools: ["Django"],
  },
  {
    id: 10,
    company: "The Air Filter Company",
    logo: "../static-job-listings-master/images/the-air-filter-company.svg",
    new: false,
    featured: false,
    position: "Front-end Dev",
    role: "Frontend",
    level: "Junior",
    timePosted: "1mo ago",
    contract: "Part Time",
    location: "Worldwide",
    progLanguage: ["JavaScript"],
    tools: ["React", "Sass"],
  },
];
